BlogWeb/BlogWeb/Controllers/HakkımdaImageController.cs
using BlogWeb.Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWeb.Controllers
{
    public class HakkımdaImageController : Controller
    {
        // GET: HakkımdaImage

        BlogWebDbEntities db = new BlogWebDbEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLHAKKIMDA.ToList();
            return View(degerler);
        }

        // HakkımdaImage güncelleme görevini yapar
        public ActionResult HakkımdaImageGetir(int id)
        {
            var hk = db.TBLHAKKIMDA.Find(id);
            return View(hk);
        }

        public ActionResult HakkımdaImageGuncelle(TBLHAKKIMDA hakkımda)
        {
            var hk = db.TBLHAKKIMDA.Find(hakkımda.ID);

            if (Request.Files.Count > 0)
            {
                string file = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "/blog_sitem/img/" + file + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                hakkımda.Resim = "/blog_sitem/img/" + file + uzanti;
            }
            hk.Resim = hakkımda.Resim;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // hakkımda Image silme görevini yapar
        public ActionResult HakkımdaSil(int id)
        {
            var hakkımda = db.TBLHAKKIMDA.Find(id);
            db.TBLHAKKIMDA.Remove(hakkımda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BlogWeb/BlogWeb/Views/HakkımdaImage/HakkımdaImageGetir.cshtml
@model BlogWeb.Models.Entity.TBLHAKKIMDA

@{
    ViewBag.Title = "HakkımdaImageGetir";
    Layout = "~/Views/Shared/Panel.cshtml";
}



<div class="container mt-5">

    <h3 class="text-center text-danger ">Hakkımda Image Güncelleme</h3>

    @using (Html.BeginForm("HakkımdaImageGuncelle", "HakkımdaImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div style="margin-top:5px;"></div>

        <div class="form-group">

            <div style="margin-bottom:10px;">

                <label>Resim :</label>
                <input class="form-control" type="file" name="Resim" id="formFileMultiple" required>

            </div>

            <button class="btn btn-success mb-5">Güncelle</button>

        </div>
    }
</div>

BlogWeb/BlogWeb/Views/HakkımdaImage/Index.cshtml
@using BlogWeb.Models.Entity
@model List<BlogWeb.Models.Entity.TBLHAKKIMDA>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Panel.cshtml";
}



<table class="table table-striped" style="margin-top:100px;">

    <tr style="background-color:rgb(252,178,22)">
        <th>Hakkımda ID</th>
        <th>Güncel Resim</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var hk in Model)
    {
        <tr>
            <td>@hk.ID</td>
            <td>
            <img src="@hk.Resim" alt="Berkayyolcu.png" style="border-radius:30%;" />
            </td>
            <td><a href="/HakkımdaImage/HakkımdaImageSil/@hk.ID" class="btn btn-danger" onclick="return sor()">Sil</a></td>
            <td><a href="/HakkımdaImage/HakkımdaImageGetir/@hk.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>