BlogWeb/BlogWeb/Controllers/MetaController.cs
using BlogWeb.Models.Entity;
using BlogWeb.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWeb.Controllers
{
    public class MetaController : Controller
    {
        // GET: Meta

        GenericRepository<TBLMETATAG> repo = new GenericRepository<TBLMETATAG>();

        BlogWebDbEntities db = new BlogWebDbEntities();


        // panelde verileri listeler
        public ActionResult Index(TBLMETATAG tag)
        {
            
            var meta = repo.list();
            return View(meta);

        }

        // meta kısmına veri ekler
        [HttpGet]
        public ActionResult MetaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MetaEkle(TBLMETATAG meta)
        {
            repo.TAdd(meta);
            return RedirectToAction("Index");
        }

        [HttpGet]
        // meta verilerini güncelleme görevini yapar
        public ActionResult MetaGetir(int id)
        {
            var meta = repo.Find(x => x.ID == id);
            return View(meta);
        }

        [HttpPost]
        public ActionResult MetaGetir(TBLMETATAG meta)
        {
            var m = repo.Find(x => x.ID == meta.ID);
            m.Abstract = meta.Abstract;
            m.Author = meta.Author;
            m.Description = meta.Description;
            m.Keywords = meta.Keywords;
            m.Title = meta.Title;
            repo.TUpdate(m);
            return RedirectToAction("Index");
        }

        // meta verileri silme görevini yapar
        public ActionResult MetaSil(int id)
        {
            var meta = repo.Find(x => x.ID == id);
            repo.Tdelete(meta);
            return RedirectToAction("Index");
        }
    }
}

BlogWeb/BlogWeb/Views/Meta/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Panel.cshtml";
}


<table class="table table-striped" style="margin-top:100px;">

    <tr style="background-color:rgb(252,178,22)">
        <th>Meta Id</th>
        <th>Site Özeti</th>
        <th>Site Yapımcısının Adı</th>
        <th>Site İceriği Acıklama</th>
        <th>Anahtar Kelimeler</th>
        <th>Site Baslık</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var meta in Model)
    {
        <tr>
            <td>@meta.ID</td>
            <td>@meta.Abstract</td>
            <td>@meta.Author</td>
            <td>@meta.Description</td>
            <td>@meta.Keywords</td>
            <td>@meta.Title</td>
            <td><a href="/Meta/MetaSil/@meta.ID" class="btn btn-danger" onclick="return sor()">Sil</a></td>
            <td><a href="/Meta/MetaGetir/@meta.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>

BlogWeb/BlogWeb/Views/Meta/MetaEkle.cshtml
@model BlogWeb.Models.Entity.TBLMETATAG
@{
    ViewBag.Title = "MetaEkle";
    Layout = "~/Views/Shared/Panel.cshtml";
}


<div class="container mt-5">

    <form class="form-group" method="post">
        <div class="row mt-5">

            <h3 class="text-center text-danger">Meta Etiketleri Ekleme</h3>

            <input type="text" class="form-control mt-2" name="Abstract" placeholder="Site özeti" />
            <input type="text" class="form-control mt-2" name="Author" placeholder="Site Yapımcısının Adı ve İletisim Bilgileri" />
            <input type="text" class="form-control mt-2" name="Description" placeholder="Site İceriği Acıklama" />
            <input type="text" class="form-control mt-2" name="Keywords" placeholder="Anahtar Kelimeler" />
            <input type="text" class="form-control mt-2" name="Title" placeholder="Site Baslık" />

        </div>
        <button class="btn btn-primary mt-2" id="Btn1">Meta Etiketi Ekle</button>
    </form>

</div>

BlogWeb/BlogWeb/Views/Meta/MetaGetir.cshtml
@model BlogWeb.Models.Entity.TBLMETATAG
@{
    ViewBag.Title = "MetaGetir";
    Layout = "~/Views/Shared/Panel.cshtml";
}


<div class="container mt-5">

    <h3 class="text-center text-danger ">Meta Bilgi Güncelleme</h3>

    @using (Html.BeginForm("MetaGetir", "Meta", FormMethod.Post))
    {
        <div style="margin-top:5px;"></div>

        <div class="form-group">

            <div style="margin-bottom:10px;">
                <label>Meta Id</label>
                @Html.TextBoxFor(k => k.ID, new { @class = "form-control", @readonly = "readonly" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Site Özeti</label>
                @Html.TextBoxFor(k => k.Abstract, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Site Yapımcısının Adı ve İletisim Bilgileri</label>
                @Html.TextBoxFor(k => k.Author, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Site İceriği Acıklama</label>
                @Html.TextBoxFor(k => k.Description, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Anahtar Kelimeler</label>
                @Html.TextBoxFor(k => k.Keywords, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Site Baslık</label>
                @Html.TextBoxFor(k => k.Title, new { @class = "form-control" })
            </div>



            <button class="btn btn-success mb-5">Güncelle</button>
        </div>
    }
</div>