BlogWeb/BlogWeb/Controllers/SosyalMedyaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogWeb.Models.Entity;
using BlogWeb.Repositories;

namespace BlogWeb.Controllers
{
    public class SosyalMedyaController : Controller
    {
        // GET: SosyalMedya
        GenericRepository<TBLSOSYALMEDYA> repo = new GenericRepository<TBLSOSYALMEDYA>();
        public ActionResult Index()
        {
            var sosyalmedya = repo.list();
            return View(sosyalmedya);
        }

        [HttpGet]
        public ActionResult SosyalMedyaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SosyalMedyaEkle(TBLSOSYALMEDYA p)
        {
            repo.TAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        // sosyal medya verilerini güncelleme görevini yapar
        public ActionResult SosyalMedyaGetir(int id)
        {
            var socialmedia = repo.Find(x => x.ID == id);
            return View(socialmedia);
        }

        [HttpPost]
        public ActionResult SosyalMedyaGetir(TBLSOSYALMEDYA p)
        {
            var s = repo.Find(x => x.ID == p.ID);
            s.AD=p.AD;
            s.LİNK = p.LİNK;
            s.İKON = p.İKON;
            repo.TUpdate(s);
            return RedirectToAction("Index");
        }

        // sosyal medya verilerini silme görevini yapar
        public ActionResult SosyalMedyaSil(int id)
        {
            var  socialmedia= repo.Find(x => x.ID == id);
            socialmedia.DURUM = false;
            repo.TUpdate(socialmedia);
            return RedirectToAction("Index");
        }


    }
}

BlogWeb/BlogWeb/Views/SosyalMedya/Index.cshtml
@using BlogWeb.Models.Entity
@model List<TBLSOSYALMEDYA>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Panel.cshtml";
}


<div class="container mt-5">

    <table class="table table-striped" style="margin-top:100px;">
        <tr style="background-color:rgb(252,178,22)">
            <th>Sosyal Medya ID</th>
            <th>Adı</th>
            <th>Link</th>
            <th>İkon</th>
            <th>Durum</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.AD</td>
                <td>@item.LİNK</td>
                <td>@item.İKON</td>
                <td>@item.DURUM</td>
                <td><a href="/SosyalMedya/SosyalMedyaSil/@item.ID" class="btn btn-danger" onclick="return sor()">Sil</a></td>
                <td><a href="/SosyalMedya/SosyalMedyaGetir/@item.ID" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </table>
    <br />
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1">Sosyal Medya Hesab Ekleme</button>
</div>

BlogWeb/BlogWeb/Views/SosyalMedya/SosyalMedyaEkle.cshtml
@model BlogWeb.Models.Entity.TBLSOSYALMEDYA
@{
    ViewBag.Title = "SosyalMedyaEkle";
    Layout = "~/Views/Shared/Panel.cshtml";
}


<div class="container mt-5">

    <div class="row mt-5">

        <form class="form-group" method="post">

            <h3 class="text-center text-danger">Sosyal Medya Hesabı Ekleme</h3>

            <input type="text" class="form-control mt-2" name="AD" placeholder="Sosyal Medya Adı" />
            <input type="text" class="form-control mt-2" name="LİNK" placeholder="Sosyal Medya Linki" />
            <input type="text" class="form-control mt-2" name="İKON" placeholder="İkon Kodunuz" />
            <input type="text" class="form-control mt-2" name="Durum" placeholder="True Yada False  Giriniz" />

            <button class="btn btn-primary mt-2">Hesab Ekle</button>
        </form>

    </div>

</div>

BlogWeb/BlogWeb/Views/SosyalMedya/SosyalMedyaGetir.cshtml
@model BlogWeb.Models.Entity.TBLSOSYALMEDYA
@{
    ViewBag.Title = "SosyalMedyaGetir";
    Layout = "~/Views/Shared/Panel.cshtml";
}


<div class="container mt-5">

    <h3 class="text-center text-danger ">Sosyal Medya Bilgi Güncelleme</h3>

    @using (Html.BeginForm("SosyalMedyaGetir", "SosyalMedya", FormMethod.Post))
    {
        <div style="margin-top:5px;"></div>

        <div class="form-group">

            <div style="margin-bottom:10px;">
                <label>Sosyal Medya Id</label>
                @Html.TextBoxFor(k => k.ID, new { @class = "form-control", @readonly = "readonly" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Sosyal Medya Adı</label>
                @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Sosyal Medya Linki</label>
                @Html.TextBoxFor(k => k.LİNK, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Sosyal Medya İkon Adı</label>
                @Html.TextBoxFor(k => k.İKON, new { @class = "form-control" })
            </div>

            <div style="margin-bottom:10px;">
                <label>Sosyal Medya Durum</label>
                @Html.TextBoxFor(k => k.DURUM, new { @class = "form-control" })
            </div>


            <button class="btn btn-success mb-5">Güncelle</button>
        </div>
    }
</div>